esphome:
  name: media-player
  friendly_name: media-player

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      # Considerably speeds up mWW at the cost of using more PSRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

      # enable psram 
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM: "y"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: "y"
      CONFIG_ESPTOOLPY_FLASHFREQ_80M: "y"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<your-key>"

ota:
  - platform: esphome
    password: "<your pass>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Media-PlayerHotspot"
    password: "bar9m1qJ8cfP"
  power_save_mode: none

captive_portal:


psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false  # The VPE has PSRAM, so this is safe. Allows configuring WiFi driver to use more resources (done automatically by the speaker media player)

 
web_server:
  port: 80
 
 
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO21 #LRCK of PCM5102
    i2s_bclk_pin: GPIO5 #BCK of PCM5102 
 
# Example configuration entry
button:
  - platform: restart
    name: "Device Restart"
 
binary_sensor:
  - platform: status                                # device status notified to home assistant for automations
    name: "Device Status"
 
 
text_sensor:
  # Send IP Address
  - platform: wifi_info
    ip_address:
      name: IP
      icon: mdi:ip-network
    ssid:
      name: SSID
      icon: mdi:router-wireless
 
    mac_address:
      name: Wifi Address
 
sensor:
  - platform: wifi_signal                      
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_signal_db
    entity_category: "diagnostic"
    internal: true  # hide this sensor to HA,
 
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    icon: mdi:wifi
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: "diagnostic"
    device_class: ""

speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: i2s_out
    dac_type: external
    i2s_dout_pin: GPIO19 #DIN Pin of PCM5102 
    sample_rate: 48000
    channel: stereo
    timeout: never
    buffer_duration: 60ms

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    num_channels: 2
    task_stack_in_psram: true
    source_speakers:
      - id: announcement_spk_mixer_input
        timeout: never
      - id: media_spk_mixer_input
        timeout: never

  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
    sample_rate: 48000    
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input
    sample_rate: 48000    

media_player:
  - platform: speaker
    name: None
    id: speaker_media_player_id
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 1.0
    # on_pause:
      # - media_player.stop
    media_pipeline:
        speaker: media_spk_resampling_input
        num_channels: 2        
    announcement_pipeline:
        speaker: announcement_spk_resampling_input
        num_channels: 1
        format: FLAC     # FLAC is the least processor intensive codec        
        sample_rate: 48000
    on_announcement:
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 20
          duration: 0.2s
      - script.execute: wait_for_announcement_end
    on_idle:
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 0
          duration: 0.5s

script:
  - id: wait_for_announcement_end
    mode: restart
    then:
      - wait_until:
          condition:
            not:
              media_player.is_announcing: speaker_media_player_id
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 0
          duration: 0.5s
